- name: lorenz
  email: looooo@users.noreply.github.com
  num_commits: 1
  first_commit: 2018-11-07 05:07:50
  github: looooo
- name: Maksim Rakitin
  email: mrakitin@bnl.gov
  alternate_emails:
  - mrakitin@users.noreply.github.com
  num_commits: 12
  first_commit: 2019-07-19 17:37:24
  github: mrakitin
- name: Gonzalo Pena-Castellanos
  email: goanpeca@gmail.com
  num_commits: 7
  first_commit: 2016-11-07 07:41:18
  github: goanpeca
- name: Matt McCormick
  email: matt.mccormick@kitware.com
  num_commits: 4
  first_commit: 2019-07-31 17:05:02
  github: thewtex
- name: John Kirkham
  email: jakirkham@gmail.com
  alternate_emails:
  - kirkhamj@janelia.hhmi.org
  aliases:
  - John Kirkham
  - jakirkham
  num_commits: 29
  first_commit: 2016-03-17 21:05:53
  github: jakirkham
- name: Daniel Bast
  email: 2790401+dbast@users.noreply.github.com
  num_commits: 16
  first_commit: 2019-08-06 12:19:03
  github: dbast
- name: Justin Calamari
  email: justin.calamari@gmail.com
  github: justcalamari
  num_commits: 10
  first_commit: 2018-03-19 17:56:17
- name: Josh Barnes
  email: joshuacookebarnes@gmail.com
  num_commits: 3
  first_commit: 2017-04-06 15:07:55
  github: jcb91
- name: Jan Schulz
  email: jasc@gmx.net
  num_commits: 11
  first_commit: 2016-01-12 03:46:58
  github: JanSchulz
- name: Tom Augspurger
  email: tom.augspurger88@gmail.com
  num_commits: 1
  first_commit: 2016-02-24 08:06:44
  github: TomAugspurger
- name: Ryan May
  email: rmay31@gmail.com
  num_commits: 1
  first_commit: 2016-04-18 15:41:35
- name: Chris Burr
  email: christopher.burr@cern.ch
  alternate_emails:
  - chrisburr@users.noreply.github.com
  num_commits: 18
  first_commit: 2019-03-20 05:10:33
  github: chrisburr
- name: Thomas Robitaille
  email: thomas.robitaille@gmail.com
  num_commits: 1
  first_commit: 2018-11-21 04:54:55
- name: John Blischak
  email: jdblischak@gmail.com
  num_commits: 7
  first_commit: 2017-11-06 16:48:18
  github: jdblischak
- name: roryk
  email: rory.kirchner@gmail.com
  num_commits: 1
  first_commit: 2018-05-02 08:59:03
  github: roryk
- name: Marius van Niekerk
  email: marius.v.niekerk@gmail.com
  aliases:
  - mariusvniekerk
  - Marius Van Niekerk
  alternate_emails:
  - marius.vanniekerk@maxpoint.com
  - mvanniekerk@flatiron.com
  num_commits: 5
  first_commit: 2017-09-15 13:37:30
  github: mariusvniekerk
- name: Carlo
  email: carlo.dri@gmail.com
  alternate_emails:
  - carlodri@users.noreply.github.com
  num_commits: 6
  first_commit: 2018-11-08 04:55:41
  github: carlodri
- name: Richard Hattersley
  email: rhattersley@gmail.com
  num_commits: 1
  first_commit: 2015-07-24 07:12:10
  github: rhattersley
- name: Filipe Fernandes
  email: ocefpaf@gmail.com
  aliases:
  - Filipe
  - ocefpaf
  num_commits: 44
  first_commit: 2015-07-27 17:51:00
  github: ocefpaf
- name: Jan Janßen
  email: janssen@mpie.de
  alternate_emails:
  - jan-janssen@users.noreply.github.com
  num_commits: 4
  first_commit: 2019-02-17 13:35:45
- name: Min RK
  email: benjaminrk@gmail.com
  num_commits: 30
  first_commit: 2016-09-15 09:07:34
  github: minrk
- name: Phil Elson
  email: pelson.pub@gmail.com
  aliases:
  - pelson
  num_commits: 96
  first_commit: 2015-04-29 03:45:25
  github: pelson
- name: Dominik Kutra
  email: k-dominik@users.noreply.github.com
  num_commits: 1
  first_commit: 2019-03-08 08:31:38
- name: Jason Furmanek
  email: furmanek@us.ibm.com
  num_commits: 10
  first_commit: 2018-08-23 17:18:32
  github: jayfurmanek
- name: Morten Enemark Lund
  email: melund@gmail.com
  num_commits: 1
  first_commit: 2016-05-09 14:48:02
  github: melund
- name: Tobias Megies
  email: megies@users.noreply.github.com
  num_commits: 3
  first_commit: 2016-08-07 06:40:44
  github: megies
- name: Guilherme Quentel Melo
  email: gqmelo@gmail.com
  num_commits: 2
  first_commit: 2016-09-22 21:25:28
  github: gqmelo
- name: santi
  email: sdvillal@gmail.com
  num_commits: 2
  first_commit: 2017-02-25 05:34:30
  github: loopbio
- name: buijennifer
  email: bui.jennifert@gmail.com
  num_commits: 2
  first_commit: 2019-07-05 16:42:47
  github: buijennifer
- name: melsyt
  email: melinda.y.song@gmail.com
  num_commits: 2
  first_commit: 2018-10-28 11:32:53
  github: melsyt
- name: gouarin
  email: loic.gouarin@gmail.com
  num_commits: 2
  first_commit: 2018-09-25 02:26:43
  github: gouarin
- name: danielballan
  email: daniel.b.allan@gmail.com
  num_commits: 1
  first_commit: 2015-11-05 11:29:33
  github: danielballan
- name: Marcel Bargull
  email: marcel.bargull@udo.edu
  alternate_emails:
  - mbargull@users.noreply.github.com
  num_commits: 34
  first_commit: 2018-07-30 05:17:51
  github: mbargull
- name: xoviat
  email: xoviat@users.noreply.github.com
  num_commits: 4
  first_commit: 2018-02-06 18:37:21
  github: ghost
- name: Max Linke
  email: max_linke@gmx.de
  num_commits: 1
  first_commit: 2017-02-12 15:31:00
- name: Nicholas Bollweg
  email: nick.bollweg@gmail.com
  num_commits: 11
  first_commit: 2019-05-20 20:03:12
  github: bollwyvl
- name: Leopold Talirz
  email: leopold.talirz@gmail.com
  num_commits: 8
  first_commit: 2019-03-15 13:06:47
  github: ltalirz
- name: Alex Goodman
  email: agoodm@users.noreply.github.com
  num_commits: 2
  first_commit: 2016-11-17 21:41:06
  github: agoodm
- name: Eric Dill
  email: edill@anaconda.com
  alternate_emails:
  - edill@bnl.gov
  - thedizzle@gmail.com
  github: ericdill
  num_commits: 13
  first_commit: 2015-09-28 14:21:52
- name: Elmar Pruesse
  email: epruesse@users.noreply.github.com
  num_commits: 4
  first_commit: 2017-05-15 15:43:01
  github: epruesse
- name: Nathan Goldbaum
  email: ngoldbau@illinois.edu
  num_commits: 1
  first_commit: 2018-06-30 19:23:41
  github: ngoldbaum
- name: Jonathan Helmus
  email: jjhelmus@gmail.com
  num_commits: 3
  first_commit: 2016-09-12 21:33:31
  github: jjhelmus
- name: Uwe L. Korn
  email: uwe.korn@quantco.com
  alternate_emails:
  - xhochy@users.noreply.github.com
  num_commits: 45
  first_commit: 2019-06-27 08:26:49
  github: xhochy
- name: C.A.M. Gerlach
  email: widenetservices@gmail.com
  num_commits: 9
  first_commit: 2018-08-05 23:33:03
- name: Isuru Fernando
  email: isuru.11@cse.mrt.ac.lk
  alternate_emails:
  - isuruf@gmail.com
  num_commits: 656
  first_commit: 2017-01-08 22:03:03
  github: isuruf
- name: Julian Rüth
  email: julian.rueth@fsfe.org
  num_commits: 18
  first_commit: 2019-01-14 22:53:11
  github: saraedum
- name: cshaley
  email: 6740446+cshaley@users.noreply.github.com
  num_commits: 1
  first_commit: 2019-07-13 12:25:19
  github: cshaley
- name: Josh Reichardt
  email: josh.reichardt@gmail.com
  num_commits: 11
  first_commit: 2019-05-06 12:02:21
- name: Michael Sarahan
  email: msarahan@gmail.com
  aliases:
  - Mike Sarahan
  num_commits: 31
  first_commit: 2016-08-19 21:04:51
  github: msarahan
- name: Matthew Craig
  email: mattwcraig@gmail.com
  aliases:
  - Matt Craig
  num_commits: 6
  first_commit: 2015-07-27 10:10:56
  github: mwcraig
- name: David Brochart
  email: david.brochart@gmail.com
  github: davidbrochart
  num_commits: 1
  first_commit: 2019-10-24 03:30:27
- name: Lion Krischer
  email: krischer@geophysik.uni-muenchen.de
  num_commits: 2
  first_commit: 2016-08-19 14:12:37
  github: krischer
- name: ap--
  email: andreas@poehlmann.io
  num_commits: 2
  first_commit: 2019-09-06 19:35:57
- name: Julien Schueller
  email: schueller@phimeca.com
  num_commits: 1
  first_commit: 2018-01-06 06:29:38
  github: jschueller
- name: Duncan Macleod
  email: duncan.macleod@ligo.org
  num_commits: 3
  first_commit: 2018-12-21 09:06:21
  github: duncanmmacleod
- name: Peter Killick
  email: peter.killick@metoffice.gov.uk
  num_commits: 2
  first_commit: 2016-09-13 05:23:00
  github: dkillick
- name: Henry Schreiner
  email: HenrySchreinerIII@gmail.com
  num_commits: 2
  first_commit: 2019-06-26 14:56:21
  github: henryiii
- name: hajapy
  email: hajapy@users.noreply.github.com
  num_commits: 2
  first_commit: 2019-08-19 20:33:42
  github: hajapy
- name: Peter Williams
  email: peter@newton.cx
  num_commits: 6
  first_commit: 2017-04-23 09:00:59
  github: pkgw
- name: Patrick Sodré
  email: sodre@sodre.co
  num_commits: 4
  first_commit: 2018-03-07 20:30:31
  github: sodre
- name: Mark Harfouche
  email: mark.harfouche@gmail.com
  num_commits: 25
  first_commit: 2018-06-12 01:15:09
  github: hmaarrfk
- name: Dougal J. Sutherland
  email: dougal@gmail.com
  github: dougalsutherland
  num_commits: 36
  first_commit: 2017-09-13 18:29:41
- name: Anthony Scopatz
  email: scopatz@gmail.com
  num_commits: 101
  first_commit: 2015-07-22 22:51:27
  github: scopatz
- name: Florian Rathgeber
  email: florian.rathgeber@gmail.com
  num_commits: 3
  first_commit: 2016-10-28 17:53:20
  github: kynan
- name: Patrick Sodré
  email: psodre@gmail.com
  num_commits: 10
  first_commit: 2018-06-02 23:19:25
  github: sodre
- name: Christopher J. Wright
  email: cjwright4242gh@gmail.com
  alternate_emails:
  - cjwright4242@gmail.com
  aliases:
  - christopher
  - Christopher J. 'CJ' Wright
  num_commits: 103
  first_commit: 2017-01-05 19:25:16
  github: CJ-Wright
- name: Jason Grout
  email: jasongrout@users.noreply.github.com
  num_commits: 1
  first_commit: 2018-07-27 01:48:05
  github: jasongrout
- name: Bruno Oliveira
  email: nicoddemus@gmail.com
  num_commits: 3
  first_commit: 2016-11-22 14:20:00
  github: nicoddemus
- name: Johannes Köster
  email: johannes.koester@tu-dortmund.de
  num_commits: 5
  first_commit: 2017-03-14 04:22:58
  github: johanneskoester
- name: Tony Kelman
  email: tony@kelman.net
  num_commits: 3
  first_commit: 2019-02-26 16:46:19
  github: tkelman
- name: refraction-ray
  email: kcanamgal@foxmail.com
  num_commits: 9
  first_commit: 2019-07-30 01:37:16
- name: shadow_walker
  email: shadowwalkersb@gmail.com
  num_commits: 33
  first_commit: 2016-08-31 23:32:44
  github: shadowwalkersb
- name: Matthew R. Becker
  email: becker.mr@gmail.com
  num_commits: 211
  first_commit: 2020-01-07 17:44:33
  github: beckermr
  alternate_emails:
  - beckermr@users.noreply.github.com
  aliases:
  - Matthew R Becker
  - beckermr
- name: Natasha Pavlovikj
  email: npavlovikj2@unl.edu
  num_commits: 13
  first_commit: 2020-01-20 13:45:51
  github: npavlovikj
- name: Tim Werner
  email: werner@inoviga.com
  num_commits: 1
  first_commit: 2020-02-12 09:02:01
- name: Dave Hirschfeld
  email: dave.hirschfeld@gmail.com
  num_commits: 1
  first_commit: 2020-03-11 10:12:57
- name: Tim Snyder
  email: snyder.tim@gmail.com
  num_commits: 14
  first_commit: 2020-03-12 12:51:58
  github: timsnyder
- name: Nils Wentzell
  email: nwentzell@flatironinstitute.org
  num_commits: 1
  first_commit: 2020-03-21 12:23:42
  github: Wentzell
- name: Leo Fang
  email: leofang@bnl.gov
  num_commits: 25
  first_commit: 2020-04-26 22:07:18
  github: leofang
  alternate_emails:
  - leo80042@gmail.com
  - leof@nvidia.com
- name: Stuart Berg
  email: bergs@janelia.hhmi.org
  num_commits: 1
  first_commit: 2020-06-28 13:24:33
  github: stuarteberg
- name: Axel Huebl
  email: axel.huebl@plasma.ninja
  num_commits: 2
  first_commit: 2020-06-06 15:29:37
  github: ax3l
- name: Hadrien Mary
  email: hadrien.mary@gmail.com
  alternate_emails:
  - hadim@users.noreply.github.com
  num_commits: 25
  first_commit: 2020-05-27 07:53:50
  github: hadim
- name: Thomas Hopkins
  email: thomashopkins000@gmail.com
  num_commits: 2
  first_commit: 2020-07-01 10:33:54
- name: Tom Pollard
  email: tom.pollard@codethink.co.uk
  num_commits: 8
  first_commit: 2020-07-09 05:47:39
- name: Ryan Volz
  email: rvolz@mit.edu
  alternate_emails:
  - ryan.volz@gmail.com
  num_commits: 25
  first_commit: 2020-07-02 12:02:36
  github: ryanvolz
- name: Joshua L. Adelman
  email: joshua.adelman@gmail.com
  num_commits: 6
  first_commit: 2020-08-10 20:50:53
  github: synapticarbors
- name: Johnny Willemsen
  email: jwillemsen@remedy.nl
  num_commits: 23
  first_commit: 2020-10-05 09:50:12
  github: jwillemsen
- name: Jaime Rodríguez-Guerra
  email: jaimergp@users.noreply.github.com
  num_commits: 180
  first_commit: 2020-11-01 14:18:08
  github: jaimergp
- name: Bastian Zimmermann
  email: 10774221+BastianZim@users.noreply.github.com
  aliases:
  - BastianZim
  num_commits: 18
  first_commit: 2021-01-27 15:01:39
  github: BastianZim
- name: Wolf Vollprecht
  email: w.vollprecht@gmail.com
  num_commits: 6
  first_commit: 2021-01-19 04:39:35
  github: wolfv
- name: Hugo Slepicka
  email: slepicka@slac.stanford.edu
  num_commits: 2
  first_commit: 2021-02-22 17:34:54
  github: hhslepicka
- name: Philippe Blain
  email: levraiphilippeblain@gmail.com
  num_commits: 5
  first_commit: 2020-06-28 18:56:49
- name: fhoehle
  email: fhoehle@users.noreply.github.com
  num_commits: 2
  first_commit: 2021-04-30 13:12:22
  github: fhoehle
- name: Ben Mares
  email: 15216687+maresb@users.noreply.github.com
  num_commits: 2
  first_commit: 2021-05-15 08:16:11
  github: maresb
- name: Billy K. Poon
  email: bkpoon@lbl.gov
  num_commits: 15
  first_commit: 2021-06-18 18:57:21
  github: bkpoon
- name: Matthias Diener
  email: mdiener@illinois.edu
  num_commits: 7
  first_commit: 2021-09-27 17:26:18
  github: matthiasdiener
- name: Matthew W. Thompson
  email: mattwthompson@protonmail.com
  num_commits: 2
  first_commit: 2021-10-21 09:39:13
  github: mattwthompson
- name: Mike Taves
  email: mwtoews@gmail.com
  num_commits: 1
  first_commit: 2021-11-02 19:52:55
  github: mwtoews
- name: Nehal J Wani
  email: nehaljw.kkd1@gmail.com
  num_commits: 1
  first_commit: 2021-11-13 10:51:42
  github: nehaljwani
- name: H. Vetinari
  email: h.vetinari@gmx.com
  num_commits: 53
  first_commit: 2021-11-14 02:53:10
- name: Benjamin Tovar
  email: btovar@nd.edu
  num_commits: 1
  first_commit: 2021-12-15 12:02:28
  github: btovar
- name: Mervin Fansler
  email: mmfansler@gmail.com
  alternate_emails:
  - fanslerm@mskcc.org
  num_commits: 5
  first_commit: 2022-02-19 13:45:48
  github: mfansler
- name: Sylvain Corlay
  email: sylvain.corlay@gmail.com
  num_commits: 1
  first_commit: 2022-03-16 16:30:25
  github: SylvainCorlay
- name: Daniel Ching
  email: carterbox@users.noreply.github.com
  num_commits: 13
  first_commit: 2022-05-11 16:57:15
  github: carterbox
- name: conda-forge-admin
  email: pelson.pub+conda-forge@gmail.com
  num_commits: 2
  first_commit: 2022-06-22 05:31:02
- name: Brandon Andersen
  email: 31670449+bandersen23@users.noreply.github.com
  num_commits: 1
  first_commit: 2022-07-03 13:55:55
  github: bandersen23
- name: Mike Henry
  email: 11765982+mikemhenry@users.noreply.github.com
  num_commits: 14
  first_commit: 2023-07-25 20:35:26
  github: mikemhenry
- name: Bela Stoyan
  email: bela.stoyan@gmail.com
  num_commits: 11
  first_commit: 2023-09-19 09:24:51
  github: '0xbe7a'
- name: Klaus Zimmermann
  email: klaus.zimmermann@smhi.se
  num_commits: 2
  first_commit: 2023-03-24 15:34:56
  github: zklaus
- name: pre-commit-ci[bot]
  email: 66853113+pre-commit-ci[bot]@users.noreply.github.com
  num_commits: 17
  first_commit: 2023-10-30 15:49:50
  github: carterbox
- name: Amit Kumar
  email: dtu.amit@gmail.com
  num_commits: 35
  first_commit: 2023-08-05 09:06:04
- name: Jannis Leidel
  email: jannis@leidel.info
  num_commits: 3
  first_commit: 2023-11-10 10:24:04
- name: David Hirschfeld
  email: david.hirschfeld@stanwell.com
  num_commits: 4
  first_commit: 2020-10-24 23:53:21
- name: Antonio S. Cofiño
  email: cofinoa@gmail.com
  num_commits: 7
  first_commit: 2024-01-08 15:21:06
  github: cofinoa
- name: vinicius douglas cerutti
  email: vinivdc2009@hotmail.com
  github: viniciusdc
  alternate_emails:
  - 51954708+viniciusdc@users.noreply.github.com
  aliases:
  - Vinicius D. Cerutti
  - viniciusdc
  num_commits: 15
  first_commit: 2023-08-03 14:24:14
- name: Yannik Tausch
  email: yannik.tausch@quantco.com
  num_commits: 7
  first_commit: 2024-03-25 05:59:00
  github: ytausch
- name: dependabot[bot]
  email: 49699333+dependabot[bot]@users.noreply.github.com
  num_commits: 2
  first_commit: 2024-05-21 04:47:22
