{% set data = load_setuptools() %}

package:
    name: conda-smithy
    version: {{ (data.get('version') or '0.1.0dev2') | replace('+', '_') | replace('/', '_') }}

source:
  path: ../

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record=record.txt
  entry_points:
    - feedstocks = conda_smithy.feedstocks:main
    - conda-smithy = conda_smithy.cli:main

requirements:
  build:
    - setuptools
    - python
  run:
    - python
    - conda-build-all
    - setuptools
    - conda
    - conda-build >=1.21.12
    - jinja2
    - requests
    - pycrypto
    - gitpython
    - pygithub <2
    - ruamel.yaml

test:
  requires:
    - nose
    - mock
  commands:
    - conda smithy --help
  imports:
    - conda_smithy
    - conda_smithy.ci_register
    - conda_smithy.configure_feedstock

about:
  home: https://github.com/conda-forge/conda-smithy
  license: BSD 3-clause
  summary: A package to create repositories for conda recipes, and automate their building with CI tools on Linux, OSX and Windows.
