# This file is just a parsable YAML that collects all the actions used by
# conda_smithy/templates/github-actions.yml.tmpl. It's here so dependabot
# can pick it up and then we can test whether the actions are up-to-date in
# the template.
on:
  workflow_dispatch:

jobs:
  inventory:
    runs-on: ubuntu-latest
    if: false
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
      - uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f # v6.0.0
